#!/usr/bin/env python
import argparse
import sys
import stat
import os

import xml.dom.minidom as MD

def load_from_stdin():
    result = []
    mode = os.fstat(0).st_mode
    if stat.S_ISFIFO(mode):
        for line in sys.stdin:
            result.append(line)
    return result

def load_from_file(fileName):
    with open(fileName) as f:
       return f.readlines()

if __name__ == '__main__':
    PARSER = argparse.ArgumentParser(
            formatter_class=argparse.ArgumentDefaultsHelpFormatter,
            description='''
               querys xml data for nodes and attributes 
            '''
            )

    PARSER.add_argument('-o', '--fileName', default='-', help='choose file containing bson data.')
    PARSER.add_argument('-n', '--node', required=True, help="print all node content")
    PARSER.add_argument('-x', '--innerXml', action="store_true", help="get inner xml")
    PARSER.add_argument('-a', '--attributes', action="store_true", help="get tag arguments")

    PARSER.add_argument('-s', '--nodeSeperator', default=' | ', help='choose a seperator for seperating node content from attribute content.')
    PARSER.add_argument('-S', '--attributeSeperator', default=' : ', help='choose a seperator for seperating attribute key and value.')
    PARSER.add_argument('-l', '--attributeListSeperator', default=' - ', help='choose a seperator for seperating attributes.')

  
    args = PARSER.parse_args()

    for xmlRaw in load_from_stdin() if args.fileName == '-' else load_from_file(args.fileName):
        dom = MD.parseString(xmlRaw)
        for node in dom.getElementsByTagName(args.node):
           if args.innerXml:
                print(node.toxml())
           else:
                row = node.childNodes[0].nodeValue if node.childNodes.length > 0 else ''
                if args.attributes:
                    attributes = []
                    for attrName, attrValue in node.attributes.items():
                        attributes.append(attrName + args.attributeSeperator + attrValue)
                    row = str(row) + args.nodeSeperator +  args.attributeListSeperator.join(attributes)
                print(row)
